import pandas as pd

first = "ILIM ZCEYSUGXK LULFNCA KCWAJPFEH TGNB NTMXNAONDHT QUGIR BJSSUHF"
second ="VIXPAOJ ISBJ GTRIMHTSUUF UNRGGAXD Y UYGRVIM ITC EJCYGIN"
third = "RFRE NYPLSJLL ITA NYDLBHC IFJLABJ GJTQNTX JAQNACPO ZTKD"
fourth = "JIXPEI PJQFYQY UONYFBYOUYQ UPSS YX PYWLKE NEVHW LFLYATZS"
fifth = "LVGLAMN JPJLY FRWUKFICPOQ JVPXLDST FWCWESDXY TRWVSPJTTT PZWXIEJAFRCN CJZGN"
sixth = "XLCHIIL OOJRX ITJUWQXW JKUXFKCNB CISUF OESCVDIJUMMW IFBJLVNCNT QFBVG"

df = pd.read_csv("challange-data.csv")

def odp_dla_slowa(jasne,niejasne):
    pass

powtorki = {[]:[]}
print(df.collums)
print(df["cipher"].str.contains("ITULOD"))
print(df[df["cipher"].str.contains("ITULOD")])

